try {
    assert 1 = 2
    Console.writeLine("failed")
}
catch e:AssertionError {
    Console.writeLine("success")
}